# Generated by Django 5.2 on 2025-06-04 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TruckModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Название модели самосвала (например, БЕЛАЗ, Komatsu)",
                        max_length=50,
                        verbose_name="Название модели",
                    ),
                ),
                (
                    "max_capacity",
                    models.PositiveIntegerField(
                        help_text="Максимальная грузоподъемность самосвала в тоннах",
                        verbose_name="Макс. грузоподъемность (т)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Модель самосвала",
                "verbose_name_plural": "Модели самосвалов",
            },
        ),
        migrations.CreateModel(
            name="Warehouse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default="Склад",
                        help_text="Название или идентификатор склада",
                        max_length=100,
                        verbose_name="Название склада",
                    ),
                ),
                (
                    "initial_weight",
                    models.FloatField(
                        help_text="Объем руды на складе до разгрузки (в тоннах)",
                        verbose_name="Начальный вес (т)",
                    ),
                ),
                (
                    "initial_si",
                    models.FloatField(
                        help_text="Начальное содержание диоксида кремния на складе (в долях, например 0.34)",
                        verbose_name="% SiO₂ (нач.)",
                    ),
                ),
                (
                    "initial_fe",
                    models.FloatField(
                        help_text="Начальное содержание железа на складе (в долях, например 0.65)",
                        verbose_name="% Fe (нач.)",
                    ),
                ),
                (
                    "area_wkt",
                    models.TextField(
                        help_text="WKT-представление полигона, определяющего границу склада",
                        verbose_name="WKT-полигон склада",
                    ),
                ),
            ],
            options={
                "verbose_name": "Склад",
                "verbose_name_plural": "Склады",
            },
        ),
        migrations.CreateModel(
            name="DumpTruck",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "board_number",
                    models.CharField(
                        help_text="Уникальный бортовой номер самосвала",
                        max_length=10,
                        unique=True,
                        verbose_name="Бортовой номер",
                    ),
                ),
                (
                    "current_weight",
                    models.FloatField(
                        help_text="Вес груза, который перевозит самосвал (в тоннах)",
                        verbose_name="Текущий вес (т)",
                    ),
                ),
                (
                    "si_percent",
                    models.FloatField(
                        help_text="Процентное содержание диоксида кремния в руде",
                        verbose_name="% SiO₂",
                    ),
                ),
                (
                    "fe_percent",
                    models.FloatField(
                        help_text="Процентное содержание железа в руде",
                        verbose_name="% Fe",
                    ),
                ),
                (
                    "unload_x",
                    models.FloatField(
                        blank=True,
                        help_text="Координата X точки разгрузки",
                        null=True,
                        verbose_name="X разгрузки",
                    ),
                ),
                (
                    "unload_y",
                    models.FloatField(
                        blank=True,
                        help_text="Координата Y точки разгрузки",
                        null=True,
                        verbose_name="Y разгрузки",
                    ),
                ),
                (
                    "model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="warehouse.truckmodel",
                        verbose_name="Модель самосвала",
                    ),
                ),
            ],
            options={
                "verbose_name": "Самосвал",
                "verbose_name_plural": "Самосвалы",
            },
        ),
    ]
